language: python
python: 
- "3.6"
script: echo 'ohuenno'
deploy:
  provider: script
  script: ssh -i travis caffeinum@testnet.exchange "cd /home/caffeinum/bots/market-maker && sudo git pull && sudo bash deploy.sh"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_9f3a35d5ff5e_key -iv $encrypted_9f3a35d5ff5e_iv
  -in travis.enc -out travis -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis
- echo -e "Host testnet.exchange\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis
